from battlefield import Battlefield

class Storyline:
    def __init__(self):
        self.battle = Battlefield

    def intro(self):
        print("Zeus was a young boy from Pallet Town. Tomorrow, Zeus will turn 10 years old and finally be able to get his Pokemon License")
        input("press any key to continue")
        print("Zeus was so excited for his birthday tomorrow that he couldn't sleep.")
        input("press any key to continue")
        print("Cronos: Zeus! Get to sleep! You will need your strength for your big day tomorrow!")
        input("press any key to continue")
        print("Zeus: I realize that father, but I can't sleep!")
        input("press any key to continue")
        print("Chronos: I can understand that my child. I was the same way when I was turning 10 as well. How about this? Let's watch this on the TV until you are tired")
        input("press any key to continue")
        print("Chronos flips on the TV and Professor Hades can be seen on the screen with Bulbasaur, Squirtile and Charmander")
        input("press any key to continue")
        print("Prof. Hades: Good evening, Pallet. Tomorrow's a big day for the newest class of Pokemon students. Here i have Bulbasaur, Charmander, and Squirtle, each availablef or new trainers. WHich one shall you choose?...")
        input("press any key to continue")
        print("Zeus stays up all night watching the TV show, excited for the big day ahead")
        input("press any key to continue")
        print("As time passes, Zeus slowly falls asleep")
        input("press any key to continue")
        print("Some more time passes, and after a while Zeus wakes up groggily")
        input("press any key to continue")
        print("After a few seconds, Zeus looks at his alarm clock and realizes he never set his alarm")
        input("press any key to continue")
        print("Zeus: Oh no! I am late!")
        input("press any key to continue")
        print("Zeus rushes outside and onward towards Professor Hades' laboratory")
        input("press any key to continue")
        print("As Zeus reaches the laboratory, a large crowd dissipates from around the building, leaving Professor Hades alone at his door step")
        input("press any key to continue")
        print("Hades: Better late than never, Zeus! I am afraid I am out of pokemon to give away today. You will have to wait a few days for the next pokemon shipment to come in from the Underworld")
        input("press any key to continue")
        print("Zeus: Oh come on Professor! Surely you have one left! I can't wait another day for my first pokemon!")
        input("press any key to continue")
        print("Hades: Hmm, well we do have one more pokemon, but I am afraid that he is a bit aggressive")
        input("press any key to continue")
        print("Zeus: That sounds perfect professor! I'll take it!")
        input("press any key to continue")
        print("Hades: Well in that case, here you go...")
        input("press any key to continue")
        print("Standing on the ground next to the professor was a small pokemon with human-like features")
        input("press any key to continue")
        print("Pokemon: HERCU, HERC!")
        input("press any key to continue")
        print("Hades: His name is Hercules.")
        input("press any key to continue")
        print("Zeus: He is perfect!")
        input("press any key to continue")
        print("Zeus reaches down to give Hercules a hug and Hercules doesn't look happy as Zeus approaches")
        input("press any key to continue")
        print("Hercules: HERCU...LEEEEES")
        input("press any key to continue")
        print("Zeus writhes in different directions as he is shocked by the Hercules")
        input("press any key to continue")
        print("Hades: I told you, you gotta watch out. Hercules has an electrifying personality.")
        input("press any key to continue")
        print("Zeus: I see what you mean Professor")
        input("press any key to continue")
        print("Suddenly, the door to the laboratory swings open and a large figure appears in the doorway")
        input("press any key to continue")
        print("King Eurystheus: Hello young adventurer, I have need of your assistance")
        input("press any key to continue")
        print("Zeus and Hades both look at the man who just walked into the doorway, confused at both his boldness and his strange attire")
        input("press any key to continue")
        print("Hades: Who are you? Also, what is with that outfit?")
        input("press any key to continue")
        print("King: There is no time to explain! I need this young man's help! Please use your new pokemon to defeat the three trials of the master!")
        input("press any key to continue")
        print("Zeus: Well you seem pretty adamant about it, I suppose I could help. What's in it for me?")
        input("press any key to continue")
        print("King: Nothing really")
        input("press any key to continue")
        print("Zeus: Well, a majority of us end up walking around this giant contintent with nothing anyways, I suppose this isn't very different. What are the tasks?")
        input("press any key to continue")
        print("King: I need you to kill the Nemean Lion, defeat the impossible nine-headed Lernaean Hydra, and capture Cerberus!")
        input("press any key to continue")
        print("Hades: Now hold on a second, Cerberus is my pokemon and spends most of his day outback basking in the sun. He wouldn't hurt a fly!")
        input("press any key to continue")
        print("Hades: Zeus, I don't like this guy, I dont think you should help him")
        input("press any key to continue")
        print("Zeus: Oh c'mon gramps, this sounds like the perfect beginning to my pokemon adventure!")
        input("press any key to continue")
        print("Hades tries to reach out to get Zeus' attention, but it is too late as Zeus has headed through the door and onwards towards his first pokemon adventure!")
        print("Intro complete")
        input("press any key to continue")


    def nem_lion(self):
        print("As Zeus wanders around in the woods nearby Pallet Town with Zeus, he is whispering to himself")
        input("press any key to continue")
        print("Zeus: I really shouldn't have run off without asking for directions first.")
        input("press any key to continue")
        print("As Zeus looks around, he sees something that looks like a ")

    def lern_hydra(self):
        pass

    def cerb(self):
        pass

    def end(self):
        pass