from battlefield import Battlefield
from hercules import Hercules
from random import randint

class Storyline:
    def __init__(self):
        self.herc = Hercules()

    def choose_reward(self):
        rew = randint(0,1)
        if rew == 1:
            self.herc.add_move()

    def run_game(self):
        # self.intro()
        self.nem_lion()

                    
    def intro(self):
        print("Zeus was a young boy from Pallet Town. Tomorrow, Zeus will turn 10 years old and finally be able to get his Pokemon License")
        input("press any key to continue")
        print("Zeus was so excited for his birthday tomorrow that he couldn't sleep.")
        input("press any key to continue")
        print("Cronos: Zeus! Get to sleep! You will need your strength for your big day tomorrow!")
        input("press any key to continue")
        print("Zeus: I realize that father, but I can't sleep!")
        input("press any key to continue")
        print("Chronos: I can understand that my child. I was the same way when I was turning 10 as well. How about this? Let's watch this on the TV until you are tired")
        input("press any key to continue")
        print("Chronos flips on the TV and Professor Hades can be seen on the screen with Bulbasaur, Squirtile and Charmander")
        input("press any key to continue")
        print("Prof. Hades: Good evening, Pallet. Tomorrow's a big day for the newest class of Pokemon students. Here i have Bulbasaur, Charmander, and Squirtle, each availablef or new trainers. WHich one shall you choose?...")
        input("press any key to continue")
        print("Zeus stays up all night watching the TV show, excited for the big day ahead")
        input("press any key to continue")
        print("As time passes, Zeus slowly falls asleep")
        input("press any key to continue")
        print("Some more time passes, and after a while Zeus wakes up groggily")
        input("press any key to continue")
        print("After a few seconds, Zeus looks at his alarm clock and realizes he never set his alarm")
        input("press any key to continue")
        print("Zeus: Oh no! I am late!")
        input("press any key to continue")
        print("Zeus rushes outside and onward towards Professor Hades' laboratory")
        input("press any key to continue")
        print("As Zeus reaches the laboratory, a large crowd dissipates from around the building, leaving Professor Hades alone at his door step")
        input("press any key to continue")
        print("Hades: Better late than never, Zeus! I am afraid I am out of pokemon to give away today. You will have to wait a few days for the next pokemon shipment to come in from the Underworld")
        input("press any key to continue")
        print("Zeus: Oh come on Professor! Surely you have one left! I can't wait another day for my first pokemon!")
        input("press any key to continue")
        print("Hades: Hmm, well we do have one more pokemon, but I am afraid that he is a bit aggressive")
        input("press any key to continue")
        print("Zeus: That sounds perfect professor! I'll take it!")
        input("press any key to continue")
        print("Hades: Well in that case, here you go...")
        input("press any key to continue")
        print("Standing on the ground next to the professor was a small pokemon with human-like features")
        input("press any key to continue")
        print("Pokemon: HERCU, HERC!")
        input("press any key to continue")
        print("Hades: His name is Hercules.")
        input("press any key to continue")
        print("Zeus: He is perfect!")
        input("press any key to continue")
        print("Zeus reaches down to give Hercules a hug and Hercules doesn't look happy as Zeus approaches")
        input("press any key to continue")
        print("Hercules: HERCU...LEEEEES")
        input("press any key to continue")
        print("Zeus writhes in different directions as he is shocked by the Hercules")
        input("press any key to continue")
        print("Hades: I told you, you gotta watch out. Hercules has an electrifying personality.")
        input("press any key to continue")
        print("Zeus: I see what you mean Professor")
        input("press any key to continue")
        print("Suddenly, the door to the laboratory swings open and a large figure appears in the doorway")
        input("press any key to continue")
        print("King Eurystheus: Hello young adventurer, I have need of your assistance")
        input("press any key to continue")
        print("Zeus and Hades both look at the man who just walked into the doorway, confused at both his boldness and his strange attire")
        input("press any key to continue")
        print("Hades: Who are you? Also, what is with that outfit?")
        input("press any key to continue")
        print("King: There is no time to explain! I need this young man's help! Please use your new pokemon to defeat the three trials of the master!")
        input("press any key to continue")
        print("Zeus: Well you seem pretty adamant about it, I suppose I could help. What's in it for me?")
        input("press any key to continue")
        print("King: Nothing really")
        input("press any key to continue")
        print("Zeus: Well, a majority of us end up walking around this giant contintent with nothing anyways, I suppose this isn't very different. What are the tasks?")
        input("press any key to continue")
        print("King: I need you to kill the Nemean Lion, defeat the impossible nine-headed Lernaean Hydra, and capture Cerberus!")
        input("press any key to continue")
        print("Hades: Now hold on a second, Cerberus is my pokemon and spends most of his day outback basking in the sun. He wouldn't hurt a fly!")
        input("press any key to continue")
        print("Hades: Zeus, I don't like this guy, I dont think you should help him")
        input("press any key to continue")
        print("Zeus: Oh c'mon gramps, this sounds like the perfect beginning to my pokemon adventure!")
        input("press any key to continue")
        print("Hades tries to reach out to get Zeus' attention, but it is too late as Zeus has headed through the door and onwards towards his first pokemon adventure!")
        print("Intro complete")
        input("press any key to continue")


    def nem_lion(self):
        print("As Zeus wanders around in the woods nearby Pallet Town with Hercules in tow, he is whispering to himself")
        input("press any key to continue")
        print("Zeus: I really shouldn't have run off without asking for directions first.")
        input("press any key to continue")
        print("As Zeus looks around, he sees something that looks like a rack of lamb, hanging from a string...in the middle of the woods")
        input("press any key to continue")
        print("Zeus: Oh Boy! Just what I needed! I am so hungry from walking around in these woods!")
        input("press any key to continue")
        print("Hercules reaches out to try to stop Zeus but its too late. Zeus grabs onto the lamb.")
        input("press any key to continue")
        print("Immediately, the ground underneath Zeus disappears and Zeus falls into a pitfall")
        input("press any key to continue")
        print("Hercules rushes over to the hole and looks inside to see Zeus incapacitated on the ground")
        input("press any key to continue")
        print("Soon after rushing over to see if Zeus was ok, a monster hops out from behind a bush!")
        input("press any key to continue")
        self.battle_one = Battlefield(1)
        self.battle_one.run_match()
        self.choose_reward()
        print("Gah! The surprise enemy yells as he is beaten")
        input("press any key to continue")
        print("Zeus crawls out of the hole, and lays down at the top of the hole for a second, catching his breathe")
        input("press any key to continue")
        print("Great job Hercules! You really showed that Goblin who was boss!")
        input("press any key to continue")
        print("Suddenly, an animal jumps out from behind another bush!")
        input("press any key to continue")
        self.battle_two = Battlefield(2)
        self.battle_two.run_match()
        self.choose_reward()
        print("Zeus: Great hit Hercules, but we have to get out of here before we get swarmed by more of those pokemon!")
        input("press any key to continue")
        print("Zeus and Hercules hurry out of the woods as fast as they can, trying to get away before any more goblins appear")
        input("press any key to continue")
        print("Eventually, they stumble out of the woods and into a clearing")
        input("press any key to continue")
        print("In the middle of the clearing is a giant statue of a lion")
        input("press any key to continue")
        print("Zeus: Whoa Hercules! We must be close to the Nemeaen Lion that that guy was talking about!")
        input("press any key to continue")
        print("The pair walk slowly up to the statue, wary that more goblins might be just around the corner")
        input("press any key to continue")
        print("Goblin Attack! They were not wary enough!")
        input("press any key to continue")
        self.battle_one = Battlefield(1)
        self.battle_one.run_match()
        self.choose_reward()
        print("Ok, these goblins have to stop attack us, this is getting kind of old")
        input("press any key to continue")
        print("Zeus did not realize, but during the scuffle between Hercules and the Goblin, the statue had come to life!")
        input("press any key to continue")
        print("Nemeaeaeaen Lion attack!")
        self.battle_four = Battlefield(4)
        self.battle_four.run_match()
        self.choose_reward()
        self.choose_reward()
        print("The pair successful defeated the Nemeaeeaeaeaean Lion!")
        input("press any key to continue")
        print("Zeus: Great job Hercules!")
        input("press any key to continue")
        print("Hercules: HERCULES!")
        input("press any key to continue")



    def lern_hydra(self):
        pass

    def cerb(self):
        pass

    def end(self):
        pass

story = Storyline()
story.run_game()